### ISSUE TITLE
请教如何实现循环 呢

### ISSUE THREAD

**Issue by hlm750908** [BolexLiu/TimeTask#3]
你好:谢谢的你的作品,请教如何实现一个 循环任务呢
我MainActivity  只有一个 浏览器控件 WebView
然后我想要 设置网址一 显示10分钟,网址2显示3分钟
一直循环 
怎么在任务1完成的时候 加任务2
任务2完成的时候  转为任务1呢
谢谢
我零java基础,因为工作才接触 android   ,比较吃力
再次感谢

**Comment by BolexLiu** [comment]
你可以再维护一个控制层，对任务列表维护。当任务被消费后，则put后面的任务进去。形成反复执行。TimeTask的职责仅仅是在某时某刻做具体的通知。
